server:
  port: ${PORT:8080}
  
info:
  component: Ebonding Push Notifications API
  
management:
  context-path: /console

routes:
  endpointRegistry: /register
  urlsBroker: /receiver
  applicationPrefix: /app
  tokenHeaderName: X-Auth
  tokenSecretKey: EA44A771237E0A1C4C2F9BB234C3A7BB70AE7CCF28542A50F75403D8EB1C096D

spring:
  redis:
    host: 192.168.99.100
    password:
    port: 6379